### ISSUE TITLE
push access for user rumbin

### ISSUE THREAD

**Issue by rumbin** [fv-kubu/fv-kubu#1]
Ich habe noch keine Push-Berechtigungen. Wäre schon gut, wenn wir nicht immer über Pull Requests gehen müssten.

@walterrenner @usinger

**Comment by walterrenner** [comment]
Einladung ist raus.

Ich habe auch allen owner Rechte für die Organisation vergeben. Dann könnt ihr bei Bedarf neuen Nutzern Rechte gewähren.

**Comment by rumbin** [comment]
Danke!
